### PR TITLE
Migrated to Kotlin

### PR DESCRIPTION
**Pull request by AshishKenjale**

### CODE REVIEW

**Comment by alvesoaj** [comment]
Wow, interesting! Why did you close it?

**Comment by AshishKenjale** [comment]
It was a mistake. Was attempting to create a PR to the forked master.

**Comment by alvesoaj** [comment]
nice! But, I guess you did it correctly.

**Comment by AshishKenjale** [comment]
I'll re-open the PR once I've finalised my changes.

**Pull request closed without merging**
